import 'package:flutter/material.dart';

List<dynamic> getJapaneseWords() {
  return [
    ['Hello', 'Konnichiwa', 'こんにちは'],
    ['Thank you', 'Arigatou', 'ありがとう'],
    ['Yes', 'Hai', 'はい'],
    ['No', 'Iie', 'いいえ'],
    ['Goodbye', 'Sayonara', 'さようなら'],
    ['Please', 'Onegai shimasu', 'おねがいします'],
    ['Sorry', 'Gomen nasai', 'ごめんなさい'],
    ['Water', 'Mizu', '水'],
    ['Food', 'Tabemono', '食べ物'],
    ['Rice', 'Gohan', 'ご飯'],
    ['Bread', 'Pan', 'パン'],
    ['Meat', 'Niku', '肉'],
    ['Fish', 'Sakana', '魚'],
    ['Vegetable', 'Yasai', '野菜'],
    ['Fruit', 'Kudamono', '果物'],
    ['Tea', 'Ocha', 'お茶'],
    ['Coffee', 'Koohii', 'コーヒー'],
    ['Milk', 'Miruku', 'ミルク'],
    ['House', 'Ie', '家'],
    ['Room', 'Heya', '部屋'],
    ['School', 'Gakkou', '学校'],
    ['Teacher', 'Sensei', '先生'],
    ['Student', 'Gakusei', '学生'],
    ['Book', 'Hon', '本'],
    ['Notebook', 'Nōto', 'ノート'],
    ['Pen', 'Pen', 'ペン'],
    ['Pencil', 'Enpitsu', '鉛筆'],
    ['Car', 'Kuruma', '車'],
    ['Bus', 'Basu', 'バス'],
    ['Train', 'Densha', '電車'],
    ['Bicycle', 'Jitensha', '自転車'],
    ['Airplane', 'Hikouki', '飛行機'],
    ['Cat', 'Neko', '猫'],
    ['Dog', 'Inu', '犬'],
    ['Bird', 'Tori', '鳥'],
    ['Fish (animal)', 'Sakana', '魚'],
    ['Mountain', 'Yama', '山'],
    ['River', 'Kawa', '川'],
    ['Sea', 'Umi', '海'],
    ['Sky', 'Sora', '空'],
    ['Sun', 'Taiyou', '太陽'],
    ['Moon', 'Tsuki', '月'],
    ['Star', 'Hoshi', '星'],
    ['Time', 'Jikan', '時間'],
    ['Day', 'Hi', '日'],
    ['Night', 'Yoru', '夜'],
    ['Today', 'Kyou', '今日'],
    ['Tomorrow', 'Ashita', '明日'],
    ['Yesterday', 'Kinou', '昨日']
  ];
}
